title: My Blog
description: A GitHub Pages blog powered by Just the Docs.
theme: just-the-docs
color_scheme: ink-blue

url: ""
baseurl: ""

permalink: pretty

collections:
  posts:
    permalink: "/blog/:year/:month/:day/:title/"
    output: true

just_the_docs:
  collections:
    posts:
      name: Blog
      nav_fold: false

plugins:
  - jekyll-feed
  - jekyll-sitemap

search_enabled: true
heading_anchors: true

nav_external_links:
  - title: Just the Docs
    url: https://just-the-docs.com
    hide_icon: false

footer_content: "Powered by <a href=\"https://just-the-docs.com\">Just the Docs</a>."

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: default
